const nflTeams = [
    { id: 1, name: '49ers', abbr: 'SF', market: 'San Francisco' },
    { id: 2, name: 'Bears', abbr: 'CHI', market: 'Chicago' },
    { id: 3, name: 'Bengals', abbr: 'CIN', market: 'Cincinnati' },
    { id: 4, name: 'Bills', abbr: 'BUF', market: 'Buffalo' },
    { id: 5, name: 'Broncos', abbr: 'DEN', market: 'Denver' },
    { id: 6, name: 'Browns', abbr: 'CLE', market: 'Cleveland' },
    { id: 7, name: 'Buccaneers', abbr: 'TB', market: 'Tampa Bay' },
    { id: 8, name: 'Cardinals', abbr: 'ARI', market: 'Arizona' },
    { id: 9, name: 'Chargers', abbr: 'LAC', market: 'Los Angeles' },
    { id: 10, name: 'Chiefs', abbr: 'KC', market: 'Kansas City' },
    { id: 11, name: 'Colts', abbr: 'IND', market: 'Indianapolis' },
    { id: 12, name: 'Commanders', abbr: 'WAS', market: 'Washington' },
    { id: 13, name: 'Cowboys', abbr: 'DAL', market: 'Dallas' },
    { id: 14, name: 'Dolphins', abbr: 'MIA', market: 'Miami' },
    { id: 15, name: 'Eagles', abbr: 'PHI', market: 'Philadelphia' },
    { id: 16, name: 'Falcons', abbr: 'ATL', market: 'Atlanta' },
    { id: 17, name: 'Giants', abbr: 'NYG', market: 'New York' },
    { id: 18, name: 'Jaguars', abbr: 'JAX', market: 'Jacksonville' },
    { id: 19, name: 'Jets', abbr: 'NYJ', market: 'New York' },
    { id: 20, name: 'Lions', abbr: 'DET', market: 'Detroit' },
    { id: 21, name: 'Packers', abbr: 'GB', market: 'Green Bay' },
    { id: 22, name: 'Panthers', abbr: 'CAR', market: 'Carolina' },
    { id: 23, name: 'Patriots', abbr: 'NE', market: 'New England' },
    { id: 24, name: 'Raiders', abbr: 'LV', market: 'Las Vegas' },
    { id: 25, name: 'Rams', abbr: 'LAR', market: 'Los Angeles' },
    { id: 26, name: 'Ravens', abbr: 'BAL', market: 'Baltimore' },
    { id: 27, name: 'Saints', abbr: 'NO', market: 'New Orleans' },
    { id: 28, name: 'Seahawks', abbr: 'SEA', market: 'Seattle' },
    { id: 29, name: 'Steelers', abbr: 'PIT', market: 'Pittsburgh' },
    { id: 30, name: 'Texans', abbr: 'HOU', market: 'Houston' },
    { id: 31, name: 'Titans', abbr: 'TEN', market: 'Tennessee' },
    { id: 32, name: 'Vikings', abbr: 'MIN', market: 'Minnesota' }
];

export const sortedNflTeams = nflTeams.sort((a, b) => a.market.localeCompare(b.market));